defmodule MobileCarWashWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :mobile_car_wash

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_mobile_car_wash_key",
    signing_salt: "gZI8tiVW",
    encryption_salt: "k3Fp9xWq",
    same_site: "Lax",
    secure: Mix.env() == :prod,
    http_only: true,
    path: "/"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, session: @session_options]],
    longpoll: [connect_info: [:peer_data, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug :static_cache_headers

  plug Plug.Static,
    at: "/",
    from: :mobile_car_wash,
    gzip: not code_reloading?,
    only: MobileCarWashWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Hashed /assets/* files never change content for a given URL, so they are
  # marked immutable. /images/* and /favicon.ico are not hashed — cache for a
  # week so rollouts aren't bottlenecked by stale logos.
  #
  # Why register_before_send: Plug.Static unconditionally overwrites
  # cache-control, so we schedule our override to run just before the response
  # is sent (after Plug.Static has already set its default).
  defp static_cache_headers(conn, _opts) do
    cache =
      case conn.request_path do
        "/assets/" <> _ -> "public, max-age=31536000, immutable"
        "/images/" <> _ -> "public, max-age=604800"
        "/fonts/" <> _ -> "public, max-age=31536000, immutable"
        "/favicon.ico" -> "public, max-age=604800"
        _ -> nil
      end

    if cache do
      Plug.Conn.register_before_send(conn, fn c ->
        Plug.Conn.put_resp_header(c, "cache-control", cache)
      end)
    else
      conn
    end
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :mobile_car_wash
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug MobileCarWashWeb.Router
end
