defmodule MobileCarWash.Repo.Migrations.AddVehicleVinBodyClass do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:vehicles) do
      add :vin, :text
      add :body_class, :text
    end
  end

  def down do
    alter table(:vehicles) do
      remove :body_class
      remove :vin
    end
  end
end
