defmodule MobileCarWash.Repo.Migrations.AddSubscriptionStripeFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subscription_plans) do
      add :stripe_price_id, :text
    end

    alter table(:customers) do
      add :stripe_customer_id, :text
    end
  end

  def down do
    alter table(:customers) do
      remove :stripe_customer_id
    end

    alter table(:subscription_plans) do
      remove :stripe_price_id
    end
  end
end
