defmodule MobileCarWash.Repo.Migrations.AppointmentBlocks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:appointment_blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :starts_at, :utc_datetime, null: false
      add :ends_at, :utc_datetime, null: false
      add :closes_at, :utc_datetime, null: false
      add :capacity, :bigint, null: false, default: 3
      add :status, :text, null: false, default: "open"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :service_type_id,
          references(:service_types,
            column: :id,
            name: "appointment_blocks_service_type_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :technician_id,
          references(:technicians,
            column: :id,
            name: "appointment_blocks_technician_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :van_id,
          references(:vans,
            column: :id,
            name: "appointment_blocks_van_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:service_types) do
      add :window_minutes, :bigint
      add :block_capacity, :bigint, null: false, default: 3
    end

    alter table(:appointments) do
      add :route_position, :bigint

      add :appointment_block_id,
          references(:appointment_blocks,
            column: :id,
            name: "appointments_appointment_block_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:appointments, "appointments_appointment_block_id_fkey")

    alter table(:appointments) do
      remove :appointment_block_id
      remove :route_position
    end

    alter table(:service_types) do
      remove :block_capacity
      remove :window_minutes
    end

    drop constraint(:appointment_blocks, "appointment_blocks_service_type_id_fkey")

    drop constraint(:appointment_blocks, "appointment_blocks_technician_id_fkey")

    drop constraint(:appointment_blocks, "appointment_blocks_van_id_fkey")

    drop table(:appointment_blocks)
  end
end
