defmodule MobileCarWash.Repo.Migrations.AddLoyaltyCards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:loyalty_cards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :punch_count, :bigint, null: false, default: 0
      add :redeemed_count, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers,
            column: :id,
            name: "loyalty_cards_customer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:loyalty_cards, [:customer_id],
             name: "loyalty_cards_unique_customer_index"
           )
  end

  def down do
    drop_if_exists unique_index(:loyalty_cards, [:customer_id],
                     name: "loyalty_cards_unique_customer_index"
                   )

    drop constraint(:loyalty_cards, "loyalty_cards_customer_id_fkey")

    drop table(:loyalty_cards)
  end
end
