defmodule MobileCarWash.Repo.Migrations.AddDeviceTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:device_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token, :text, null: false
      add :platform, :text, null: false, default: "ios"
      add :active, :boolean, null: false, default: true
      add :app_version, :text
      add :device_model, :text
      add :last_seen_at, :utc_datetime_usec
      add :failed_at, :utc_datetime_usec
      add :failure_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers,
            column: :id,
            name: "device_tokens_customer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:device_tokens, [:token], name: "device_tokens_unique_token_index")
  end

  def down do
    drop_if_exists unique_index(:device_tokens, [:token],
                     name: "device_tokens_unique_token_index"
                   )

    drop constraint(:device_tokens, "device_tokens_customer_id_fkey")

    drop table(:device_tokens)
  end
end
