defmodule MobileCarWash.Repo.Migrations.AddStepTimers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:checklist_items) do
      add :estimated_minutes, :bigint
      add :started_at, :utc_datetime
      add :actual_seconds, :bigint
    end
  end

  def down do
    alter table(:checklist_items) do
      remove :actual_seconds
      remove :started_at
      remove :estimated_minutes
    end
  end
end
