defmodule MobileCarWash.Repo.Migrations.CreateAppointmentAddOns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:appointment_add_ons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :price_cents, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :appointment_id,
          references(:appointments,
            column: :id,
            name: "appointment_add_ons_appointment_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :add_on_id,
          references(:add_ons,
            column: :id,
            name: "appointment_add_ons_add_on_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:appointment_add_ons, "appointment_add_ons_appointment_id_fkey")

    drop constraint(:appointment_add_ons, "appointment_add_ons_add_on_id_fkey")

    drop table(:appointment_add_ons)
  end
end
