defmodule MobileCarWash.Repo.Migrations.AddReferralFieldsToCustomers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers) do
      add :referral_code, :text
      add :referral_credit_cents, :bigint, null: false, default: 0

      add :referred_by_id,
          references(:customers,
            column: :id,
            name: "customers_referred_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:customers, [:referral_code],
             name: "customers_unique_referral_code_index"
           )
  end

  def down do
    drop_if_exists unique_index(:customers, [:referral_code],
                     name: "customers_unique_referral_code_index"
                   )

    drop constraint(:customers, "customers_referred_by_id_fkey")

    alter table(:customers) do
      remove :referred_by_id
      remove :referral_credit_cents
      remove :referral_code
    end
  end
end
