defmodule MobileCarWash.Repo.Migrations.AddPaymentCompFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:payments) do
      add :collected_cents, :bigint
      add :comped, :boolean, null: false, default: false
      add :comp_reason, :text
    end

    execute("UPDATE payments SET collected_cents = amount_cents WHERE collected_cents IS NULL AND status = 'succeeded'")
  end

  def down do
    alter table(:payments) do
      remove :comp_reason
      remove :comped
      remove :collected_cents
    end
  end
end
