defmodule MobileCarWash.Repo.Migrations.AddTechUserLink do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:technicians) do
      add :user_account_id,
          references(:customers,
            column: :id,
            name: "technicians_user_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:technicians, "technicians_user_account_id_fkey")

    alter table(:technicians) do
      remove :user_account_id
    end
  end
end
