defmodule MobileCarWash.Repo.Migrations.CreateMarketingSpends do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:marketing_spends, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :spent_on, :date, null: false
      add :amount_cents, :bigint, null: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :channel_id,
          references(:acquisition_channels,
            column: :id,
            name: "marketing_spends_channel_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end
  end

  def down do
    drop constraint(:marketing_spends, "marketing_spends_channel_id_fkey")

    drop table(:marketing_spends)
  end
end
