defmodule MobileCarWash.Repo.Migrations.AddComplianceDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:task_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :sort_order, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:task_categories, [:slug], name: "task_categories_unique_slug_index")

    create table(:formation_tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "not_started"
      add :priority, :text, default: "medium"
      add :due_date, :date
      add :completed_at, :utc_datetime
      add :notes, :text
      add :external_url, :text
      add :recurring, :boolean, default: false
      add :recurrence_months, :bigint, default: 12

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :category_id,
          references(:task_categories,
            column: :id,
            name: "formation_tasks_category_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :parent_task_id,
          references(:formation_tasks,
            column: :id,
            name: "formation_tasks_parent_task_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:formation_tasks, "formation_tasks_category_id_fkey")

    drop constraint(:formation_tasks, "formation_tasks_parent_task_id_fkey")

    drop table(:formation_tasks)

    drop_if_exists unique_index(:task_categories, [:slug],
                     name: "task_categories_unique_slug_index"
                   )

    drop table(:task_categories)
  end
end
