defmodule MobileCarWash.Repo.Migrations.CreateCookieConsents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cookie_consents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :essential, :boolean, null: false, default: true
      add :analytics, :boolean, null: false, default: false
      add :marketing, :boolean, null: false, default: false
      add :source, :text, default: "banner"
      add :ip_hash, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers,
            column: :id,
            name: "cookie_consents_customer_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:cookie_consents, "cookie_consents_customer_id_fkey")

    drop table(:cookie_consents)
  end
end
