defmodule MobileCarWash.Repo.Migrations.AddAttributionToCustomers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers) do
      add :utm_source, :text
      add :utm_medium, :text
      add :utm_campaign, :text
      add :utm_content, :text
      add :referrer, :text
      add :acquired_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")

      add :acquired_channel_id,
          references(:acquisition_channels,
            column: :id,
            name: "customers_acquired_channel_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:customers, "customers_acquired_channel_id_fkey")

    alter table(:customers) do
      remove :acquired_channel_id
      remove :acquired_at
      remove :referrer
      remove :utm_content
      remove :utm_campaign
      remove :utm_medium
      remove :utm_source
    end
  end
end
