defmodule MobileCarWash.Repo.Migrations.CreatePersonasAndMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:personas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :name, :text, null: false
      add :description, :text, null: false, default: ""
      add :criteria, :map, default: %{}
      add :image_url, :text
      add :image_prompt, :text
      add :active, :boolean, null: false, default: true
      add :sort_order, :bigint, default: 100

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:personas, [:slug], name: "personas_unique_slug_index")

    create table(:persona_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :matched_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :manually_assigned, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers,
            column: :id,
            name: "persona_memberships_customer_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :persona_id,
          references(:personas,
            column: :id,
            name: "persona_memberships_persona_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:persona_memberships, [:customer_id, :persona_id],
             name: "persona_memberships_unique_pair_index"
           )
  end

  def down do
    drop_if_exists unique_index(:persona_memberships, [:customer_id, :persona_id],
                     name: "persona_memberships_unique_pair_index"
                   )

    drop constraint(:persona_memberships, "persona_memberships_customer_id_fkey")

    drop constraint(:persona_memberships, "persona_memberships_persona_id_fkey")

    drop table(:persona_memberships)

    drop_if_exists unique_index(:personas, [:slug], name: "personas_unique_slug_index")

    drop table(:personas)
  end
end
