defmodule MobileCarWash.Repo.Migrations.CreateBlockedDates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:blocked_dates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :date, :date, null: false
      add :reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:blocked_dates, [:date], name: "blocked_dates_unique_date_index")
  end

  def down do
    drop_if_exists unique_index(:blocked_dates, [:date], name: "blocked_dates_unique_date_index")

    drop table(:blocked_dates)
  end
end
