defmodule MobileCarWash.Repo.Migrations.AddZoneFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:technicians) do
      add :zone, :text
    end

    alter table(:addresses) do
      add :zone, :text
    end
  end

  def down do
    alter table(:addresses) do
      remove :zone
    end

    alter table(:technicians) do
      remove :zone
    end
  end
end
