defmodule MobileCarWash.Repo.Migrations.StripeCatalogFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:service_types) do
      add :stripe_product_id, :text
      add :stripe_price_id, :text
    end

    alter table(:subscription_plans) do
      add :stripe_product_id, :text
    end
  end

  def down do
    alter table(:subscription_plans) do
      remove :stripe_product_id
    end

    alter table(:service_types) do
      remove :stripe_price_id
      remove :stripe_product_id
    end
  end
end
