defmodule MobileCarWash.Repo.Migrations.AddPushOptIn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers) do
      add :push_opt_in, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:customers) do
      remove :push_opt_in
    end
  end
end
