defmodule MobileCarWash.Repo.Migrations.AddPhotoAiTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:photos) do
      add :ai_tags, :map
      add :ai_processed_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:photos) do
      remove :ai_processed_at
      remove :ai_tags
    end
  end
end
