defmodule MobileCarWash.Repo.Migrations.AddSmsOptInToCustomers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers) do
      add :sms_opt_in, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:customers) do
      remove :sms_opt_in
    end
  end
end
