defmodule MobileCarWash.Repo.Migrations.AddStripeCheckoutSessionId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:payments) do
      add :stripe_checkout_session_id, :text
    end
  end

  def down do
    alter table(:payments) do
      remove :stripe_checkout_session_id
    end
  end
end
