defmodule MobileCarWash.Repo.Migrations.AddRecurringScheduleAddOns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:recurring_schedule_add_ons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :recurring_schedule_id,
          references(:recurring_schedules,
            column: :id,
            name: "recurring_schedule_add_ons_recurring_schedule_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :add_on_id,
          references(:add_ons,
            column: :id,
            name: "recurring_schedule_add_ons_add_on_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(
           :recurring_schedule_add_ons,
           "recurring_schedule_add_ons_recurring_schedule_id_fkey"
         )

    drop constraint(:recurring_schedule_add_ons, "recurring_schedule_add_ons_add_on_id_fkey")

    drop table(:recurring_schedule_add_ons)
  end
end
