defmodule MobileCarWash.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vehicles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :make, :text, null: false
      add :model, :text, null: false
      add :year, :bigint
      add :color, :text
      add :size, :text, default: "sedan"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id, :uuid, null: false
    end

    create table(:vans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :license_plate, :text
      add :active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:technicians, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :phone, :text
      add :active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :van_id, references(:vans, column: :id, name: "technicians_van_id_fkey", type: :uuid)
    end

    create table(:subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :stripe_subscription_id, :text
      add :status, :text, null: false, default: "active"
      add :current_period_start, :date
      add :current_period_end, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id, :uuid, null: false
      add :plan_id, :uuid, null: false
    end

    create table(:subscription_usages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :period_start, :date, null: false
      add :period_end, :date, null: false
      add :basic_washes_used, :bigint, default: 0
      add :deep_cleans_used, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :subscription_id,
          references(:subscriptions,
            column: :id,
            name: "subscription_usages_subscription_id_fkey",
            type: :uuid
          ),
          null: false
    end

    create table(:subscription_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :price_cents, :bigint, null: false
      add :basic_washes_per_month, :bigint, null: false, default: 0
      add :deep_cleans_per_month, :bigint, null: false, default: 0
      add :deep_clean_discount_percent, :bigint, null: false, default: 0
      add :description, :text
      add :active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:subscription_plans, [:slug],
             name: "subscription_plans_unique_slug_index"
           )

    create table(:service_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :base_price_cents, :bigint, null: false
      add :duration_minutes, :bigint, null: false
      add :active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:service_types, [:slug], name: "service_types_unique_slug_index")

    create table(:payments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :stripe_payment_intent_id, :text
      add :amount_cents, :bigint, null: false
      add :status, :text, null: false, default: "pending"
      add :paid_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id, :uuid, null: false
      add :appointment_id, :uuid
      add :subscription_id, :uuid
    end

    create table(:experiments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :hypothesis, :text
      add :status, :text, null: false, default: "draft"
      add :variants, :map
      add :started_at, :utc_datetime
      add :concluded_at, :utc_datetime
      add :results, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:experiments, [:name], name: "experiments_unique_name_index")

    create table(:experiment_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :variant, :text, null: false

      add :assigned_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :experiment_id,
          references(:experiments,
            column: :id,
            name: "experiment_assignments_experiment_id_fkey",
            type: :uuid
          ),
          null: false
    end

    create unique_index(:experiment_assignments, [:session_id, :experiment_id],
             name: "experiment_assignments_unique_session_experiment_index"
           )

    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :event_name, :text, null: false
      add :source, :text, default: "web"
      add :properties, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id, :uuid
    end

    create table(:customers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:vehicles) do
      modify :customer_id,
             references(:customers, column: :id, name: "vehicles_customer_id_fkey", type: :uuid)
    end

    alter table(:subscriptions) do
      modify :customer_id,
             references(:customers,
               column: :id,
               name: "subscriptions_customer_id_fkey",
               type: :uuid
             )

      modify :plan_id,
             references(:subscription_plans,
               column: :id,
               name: "subscriptions_plan_id_fkey",
               type: :uuid
             )
    end

    alter table(:payments) do
      modify :customer_id,
             references(:customers, column: :id, name: "payments_customer_id_fkey", type: :uuid)
    end

    alter table(:events) do
      modify :customer_id,
             references(:customers, column: :id, name: "events_customer_id_fkey", type: :uuid)
    end

    alter table(:customers) do
      add :email, :citext, null: false
      add :name, :text, null: false
      add :phone, :text
      add :hashed_password, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:customers, [:email], name: "customers_unique_email_index")

    create table(:audit_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :actor_id, :uuid
      add :actor_type, :text, default: "system"
      add :action, :text, null: false
      add :resource_type, :text, null: false
      add :resource_id, :uuid
      add :metadata, :map, default: %{}
      add :changes, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:appointments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:payments) do
      modify :appointment_id,
             references(:appointments,
               column: :id,
               name: "payments_appointment_id_fkey",
               type: :uuid
             )

      modify :subscription_id,
             references(:subscriptions,
               column: :id,
               name: "payments_subscription_id_fkey",
               type: :uuid
             )
    end

    alter table(:appointments) do
      add :scheduled_at, :utc_datetime, null: false
      add :duration_minutes, :bigint, null: false
      add :status, :text, null: false, default: "pending"
      add :price_cents, :bigint, null: false
      add :discount_cents, :bigint, default: 0
      add :notes, :text
      add :cancellation_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers, column: :id, name: "appointments_customer_id_fkey", type: :uuid),
          null: false

      add :vehicle_id,
          references(:vehicles, column: :id, name: "appointments_vehicle_id_fkey", type: :uuid),
          null: false

      add :address_id, :uuid, null: false
      add :service_type_id, :uuid, null: false
      add :technician_id, :uuid
    end

    create table(:addresses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:appointments) do
      modify :address_id,
             references(:addresses,
               column: :id,
               name: "appointments_address_id_fkey",
               type: :uuid
             )

      modify :service_type_id,
             references(:service_types,
               column: :id,
               name: "appointments_service_type_id_fkey",
               type: :uuid
             )

      modify :technician_id,
             references(:technicians,
               column: :id,
               name: "appointments_technician_id_fkey",
               type: :uuid
             )
    end

    alter table(:addresses) do
      add :street, :text, null: false
      add :city, :text, null: false
      add :state, :text, null: false, default: "TX"
      add :zip, :text, null: false
      add :latitude, :float
      add :longitude, :float
      add :is_default, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers, column: :id, name: "addresses_customer_id_fkey", type: :uuid),
          null: false
    end
  end

  def down do
    drop constraint(:addresses, "addresses_customer_id_fkey")

    alter table(:addresses) do
      remove :customer_id
      remove :updated_at
      remove :inserted_at
      remove :is_default
      remove :longitude
      remove :latitude
      remove :zip
      remove :state
      remove :city
      remove :street
    end

    drop constraint(:appointments, "appointments_address_id_fkey")

    drop constraint(:appointments, "appointments_service_type_id_fkey")

    drop constraint(:appointments, "appointments_technician_id_fkey")

    alter table(:appointments) do
      modify :technician_id, :uuid
      modify :service_type_id, :uuid
      modify :address_id, :uuid
    end

    drop table(:addresses)

    drop constraint(:appointments, "appointments_customer_id_fkey")

    drop constraint(:appointments, "appointments_vehicle_id_fkey")

    alter table(:appointments) do
      remove :technician_id
      remove :service_type_id
      remove :address_id
      remove :vehicle_id
      remove :customer_id
      remove :updated_at
      remove :inserted_at
      remove :cancellation_reason
      remove :notes
      remove :discount_cents
      remove :price_cents
      remove :status
      remove :duration_minutes
      remove :scheduled_at
    end

    drop constraint(:payments, "payments_appointment_id_fkey")

    drop constraint(:payments, "payments_subscription_id_fkey")

    alter table(:payments) do
      modify :subscription_id, :uuid
      modify :appointment_id, :uuid
    end

    drop table(:appointments)

    drop table(:audit_logs)

    drop_if_exists unique_index(:customers, [:email], name: "customers_unique_email_index")

    alter table(:customers) do
      remove :updated_at
      remove :inserted_at
      remove :hashed_password
      remove :phone
      remove :name
      remove :email
    end

    drop constraint(:events, "events_customer_id_fkey")

    alter table(:events) do
      modify :customer_id, :uuid
    end

    drop constraint(:payments, "payments_customer_id_fkey")

    alter table(:payments) do
      modify :customer_id, :uuid
    end

    drop constraint(:subscriptions, "subscriptions_customer_id_fkey")

    drop constraint(:subscriptions, "subscriptions_plan_id_fkey")

    alter table(:subscriptions) do
      modify :plan_id, :uuid
      modify :customer_id, :uuid
    end

    drop constraint(:vehicles, "vehicles_customer_id_fkey")

    alter table(:vehicles) do
      modify :customer_id, :uuid
    end

    drop table(:customers)

    drop table(:events)

    drop_if_exists unique_index(:experiment_assignments, [:session_id, :experiment_id],
                     name: "experiment_assignments_unique_session_experiment_index"
                   )

    drop constraint(:experiment_assignments, "experiment_assignments_experiment_id_fkey")

    drop table(:experiment_assignments)

    drop_if_exists unique_index(:experiments, [:name], name: "experiments_unique_name_index")

    drop table(:experiments)

    drop table(:payments)

    drop_if_exists unique_index(:service_types, [:slug], name: "service_types_unique_slug_index")

    drop table(:service_types)

    drop_if_exists unique_index(:subscription_plans, [:slug],
                     name: "subscription_plans_unique_slug_index"
                   )

    drop table(:subscription_plans)

    drop constraint(:subscription_usages, "subscription_usages_subscription_id_fkey")

    drop table(:subscription_usages)

    drop table(:subscriptions)

    drop constraint(:technicians, "technicians_van_id_fkey")

    drop table(:technicians)

    drop table(:tokens)

    drop table(:vans)

    drop table(:vehicles)
  end
end
