defmodule MobileCarWash.Repo.Migrations.AddTagsAndCustomerTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:customer_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers,
            column: :id,
            name: "customer_tags_customer_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :tag_id, :uuid, null: false
      add :author_id, :uuid
    end

    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:customer_tags) do
      modify :tag_id,
             references(:tags,
               column: :id,
               name: "customer_tags_tag_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :author_id,
             references(:customers,
               column: :id,
               name: "customer_tags_author_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    create unique_index(:customer_tags, [:customer_id, :tag_id],
             name: "customer_tags_unique_pair_index"
           )

    alter table(:tags) do
      add :slug, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :color, :text, null: false, default: "neutral"
      add :icon, :text
      add :affects_booking, :boolean, null: false, default: false
      add :protected, :boolean, null: false, default: false
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tags, [:slug], name: "tags_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:tags, [:slug], name: "tags_unique_slug_index")

    alter table(:tags) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :protected
      remove :affects_booking
      remove :icon
      remove :color
      remove :description
      remove :name
      remove :slug
    end

    drop_if_exists unique_index(:customer_tags, [:customer_id, :tag_id],
                     name: "customer_tags_unique_pair_index"
                   )

    drop constraint(:customer_tags, "customer_tags_tag_id_fkey")

    drop constraint(:customer_tags, "customer_tags_author_id_fkey")

    alter table(:customer_tags) do
      modify :author_id, :uuid
      modify :tag_id, :uuid
    end

    drop table(:tags)

    drop constraint(:customer_tags, "customer_tags_customer_id_fkey")

    drop table(:customer_tags)
  end
end
