defmodule MobileCarWash.Repo.Migrations.CreateRecurringSchedules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:recurring_schedules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :frequency, :text, null: false
      add :preferred_day, :bigint, null: false
      add :preferred_time, :time, null: false
      add :active, :boolean, null: false, default: true
      add :last_scheduled_date, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers,
            column: :id,
            name: "recurring_schedules_customer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :vehicle_id,
          references(:vehicles,
            column: :id,
            name: "recurring_schedules_vehicle_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :address_id,
          references(:addresses,
            column: :id,
            name: "recurring_schedules_address_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :service_type_id,
          references(:service_types,
            column: :id,
            name: "recurring_schedules_service_type_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :subscription_id,
          references(:subscriptions,
            column: :id,
            name: "recurring_schedules_subscription_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:recurring_schedules, "recurring_schedules_customer_id_fkey")

    drop constraint(:recurring_schedules, "recurring_schedules_vehicle_id_fkey")

    drop constraint(:recurring_schedules, "recurring_schedules_address_id_fkey")

    drop constraint(:recurring_schedules, "recurring_schedules_service_type_id_fkey")

    drop constraint(:recurring_schedules, "recurring_schedules_subscription_id_fkey")

    drop table(:recurring_schedules)
  end
end
