defmodule MobileCarWash.Repo.Migrations.AddDisabledToCustomers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers) do
      add :disabled_at, :utc_datetime_usec
      add :disabled_reason, :text
    end
  end

  def down do
    alter table(:customers) do
      remove :disabled_reason
      remove :disabled_at
    end
  end
end
