defmodule MobileCarWash.Repo.Migrations.AddPhotos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:photos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :file_path, :text, null: false
      add :original_filename, :text
      add :content_type, :text
      add :photo_type, :text, null: false
      add :caption, :text
      add :uploaded_by, :text, default: "technician"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :appointment_id,
          references(:appointments,
            column: :id,
            name: "photos_appointment_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :checklist_item_id,
          references(:checklist_items,
            column: :id,
            name: "photos_checklist_item_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:photos, "photos_appointment_id_fkey")

    drop constraint(:photos, "photos_checklist_item_id_fkey")

    drop table(:photos)
  end
end
