defmodule MobileCarWash.Repo.Migrations.EnrichEventsWithDeviceMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :device_type, :text, default: "unknown"
      add :os, :text
      add :browser, :text
      add :user_agent, :text
      add :page_path, :text
    end
  end

  def down do
    alter table(:events) do
      remove :page_path
      remove :user_agent
      remove :browser
      remove :os
      remove :device_type
    end
  end
end
