defmodule MobileCarWash.Repo.Migrations.AddTechPay do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:technicians) do
      add :pay_rate_cents, :bigint, default: 2500
      add :pay_period_start_day, :bigint, default: 1
    end
  end

  def down do
    alter table(:technicians) do
      remove :pay_period_start_day
      remove :pay_rate_cents
    end
  end
end
