defmodule MobileCarWash.Repo.Migrations.AddSupplies do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:supplies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :category, :text, null: false, default: "other"
      add :unit, :text, null: false, default: "units"
      add :quantity_on_hand, :decimal, null: false, default: "0"
      add :low_stock_threshold, :decimal
      add :unit_cost_cents, :bigint
      add :supplier, :text
      add :notes, :text
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:supplies)
  end
end
