defmodule MobileCarWash.Repo.Migrations.CreateAddOns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:add_ons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :price_cents, :bigint, null: false
      add :icon, :text
      add :active, :boolean, default: true
      add :sort_order, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:add_ons, [:slug], name: "add_ons_unique_slug_index")
    # NOTE: :photos idempotency_key and deleted_at were already added by
    # 20260523200020_add_photo_idempotency_and_soft_delete.exs (manual Ecto migration).
    # Removed from this migration to avoid "column already exists" errors.
  end

  def down do
    drop_if_exists unique_index(:add_ons, [:slug], name: "add_ons_unique_slug_index")

    drop table(:add_ons)
  end
end
