defmodule MobileCarWash.Repo.Migrations.AddReferralCodeUsedToAppointments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      add :referral_code_used, :text
    end
  end

  def down do
    alter table(:appointments) do
      remove :referral_code_used
    end
  end
end
