defmodule MobileCarWash.Repo.Migrations.AddRecurringScheduleIdToAppointments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      add :recurring_schedule_id,
          references(:recurring_schedules,
            column: :id,
            name: "appointments_recurring_schedule_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:appointments, "appointments_recurring_schedule_id_fkey")

    alter table(:appointments) do
      remove :recurring_schedule_id
    end
  end
end
