defmodule MobileCarWash.Repo.Migrations.AddCustomerNotes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:customer_notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false
      add :pinned, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers,
            column: :id,
            name: "customer_notes_customer_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :author_id,
          references(:customers,
            column: :id,
            name: "customer_notes_author_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:customer_notes, "customer_notes_customer_id_fkey")

    drop constraint(:customer_notes, "customer_notes_author_id_fkey")

    drop table(:customer_notes)
  end
end
