defmodule MobileCarWash.Repo.Migrations.AddEmythSystems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:procedures, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :category, :text, default: "wash"
      add :active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :service_type_id,
          references(:service_types,
            column: :id,
            name: "procedures_service_type_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:procedures, [:slug], name: "procedures_unique_slug_index")

    create table(:procedure_steps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :step_number, :bigint, null: false
      add :title, :text, null: false
      add :description, :text
      add :estimated_minutes, :bigint
      add :required, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :procedure_id,
          references(:procedures,
            column: :id,
            name: "procedure_steps_procedure_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:position_contracts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :purpose, :text
      add :responsibilities, :text
      add :standards, :text
      add :active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :position_id, :uuid, null: false
    end

    create table(:org_positions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:position_contracts) do
      modify :position_id,
             references(:org_positions,
               column: :id,
               name: "position_contracts_position_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:org_positions) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :level, :bigint, default: 0
      add :sort_order, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parent_position_id,
          references(:org_positions,
            column: :id,
            name: "org_positions_parent_position_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:org_positions, [:slug], name: "org_positions_unique_slug_index")

    create table(:checklist_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :step_number, :bigint, null: false
      add :title, :text, null: false
      add :description, :text
      add :required, :boolean, default: true
      add :completed, :boolean, default: false
      add :completed_at, :utc_datetime
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :checklist_id, :uuid, null: false
      add :procedure_step_id, :uuid, null: false
    end

    create table(:appointment_checklists, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:checklist_items) do
      modify :checklist_id,
             references(:appointment_checklists,
               column: :id,
               name: "checklist_items_checklist_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :procedure_step_id,
             references(:procedure_steps,
               column: :id,
               name: "checklist_items_procedure_step_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:appointment_checklists) do
      add :status, :text, null: false, default: "not_started"
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :appointment_id,
          references(:appointments,
            column: :id,
            name: "appointment_checklists_appointment_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :procedure_id,
          references(:procedures,
            column: :id,
            name: "appointment_checklists_procedure_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:appointment_checklists, "appointment_checklists_appointment_id_fkey")

    drop constraint(:appointment_checklists, "appointment_checklists_procedure_id_fkey")

    alter table(:appointment_checklists) do
      remove :procedure_id
      remove :appointment_id
      remove :updated_at
      remove :inserted_at
      remove :completed_at
      remove :started_at
      remove :status
    end

    drop constraint(:checklist_items, "checklist_items_checklist_id_fkey")

    drop constraint(:checklist_items, "checklist_items_procedure_step_id_fkey")

    alter table(:checklist_items) do
      modify :procedure_step_id, :uuid
      modify :checklist_id, :uuid
    end

    drop table(:appointment_checklists)

    drop table(:checklist_items)

    drop_if_exists unique_index(:org_positions, [:slug], name: "org_positions_unique_slug_index")

    drop constraint(:org_positions, "org_positions_parent_position_id_fkey")

    alter table(:org_positions) do
      remove :parent_position_id
      remove :updated_at
      remove :inserted_at
      remove :sort_order
      remove :level
      remove :description
      remove :slug
      remove :name
    end

    drop constraint(:position_contracts, "position_contracts_position_id_fkey")

    alter table(:position_contracts) do
      modify :position_id, :uuid
    end

    drop table(:org_positions)

    drop table(:position_contracts)

    drop constraint(:procedure_steps, "procedure_steps_procedure_id_fkey")

    drop table(:procedure_steps)

    drop_if_exists unique_index(:procedures, [:slug], name: "procedures_unique_slug_index")

    drop constraint(:procedures, "procedures_service_type_id_fkey")

    drop table(:procedures)
  end
end
