defmodule MobileCarWash.Repo.Migrations.CashFlowSystem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cash_flow_transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :amount_cents, :bigint, null: false
      add :description, :text

      add :occurred_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :from_account_id, :uuid
      add :to_account_id, :uuid
    end

    create table(:cash_flow_config, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :monthly_opex_cents, :bigint, null: false, default: 0
      add :salary_cents, :bigint, null: false, default: 0
      add :investment_target_cents, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:cash_flow_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:cash_flow_transactions) do
      modify :from_account_id,
             references(:cash_flow_accounts,
               column: :id,
               name: "cash_flow_transactions_from_account_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :to_account_id,
             references(:cash_flow_accounts,
               column: :id,
               name: "cash_flow_transactions_to_account_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:cash_flow_accounts) do
      add :account_type, :text, null: false
      add :name, :text, null: false
      add :balance_cents, :bigint, null: false, default: 0
      add :color, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:cash_flow_accounts, [:account_type],
             name: "cash_flow_accounts_unique_type_index"
           )
  end

  def down do
    drop_if_exists unique_index(:cash_flow_accounts, [:account_type],
                     name: "cash_flow_accounts_unique_type_index"
                   )

    alter table(:cash_flow_accounts) do
      remove :updated_at
      remove :inserted_at
      remove :color
      remove :balance_cents
      remove :name
      remove :account_type
    end

    drop constraint(:cash_flow_transactions, "cash_flow_transactions_from_account_id_fkey")

    drop constraint(:cash_flow_transactions, "cash_flow_transactions_to_account_id_fkey")

    alter table(:cash_flow_transactions) do
      modify :to_account_id, :uuid
      modify :from_account_id, :uuid
    end

    drop table(:cash_flow_accounts)

    drop table(:cash_flow_config)

    drop table(:cash_flow_transactions)
  end
end
