defmodule MobileCarWash.Repo.Migrations.AddTechPayRatePct do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:technicians) do
      add :pay_rate_pct, :decimal
    end
  end

  def down do
    alter table(:technicians) do
      remove :pay_rate_pct
    end
  end
end
