defmodule MobileCarWash.Repo.Migrations.CreateAcquisitionChannels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acquisition_channels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :display_name, :text, null: false
      add :category, :text, null: false
      add :active, :boolean, null: false, default: true
      add :sort_order, :bigint, default: 100

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:acquisition_channels, [:slug],
             name: "acquisition_channels_unique_slug_index"
           )
  end

  def down do
    drop_if_exists unique_index(:acquisition_channels, [:slug],
                     name: "acquisition_channels_unique_slug_index"
                   )

    drop table(:acquisition_channels)
  end
end
