defmodule MobileCarWash.Repo.Migrations.AddReferralRewardIssuedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers) do
      add :referral_reward_issued_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:customers) do
      remove :referral_reward_issued_at
    end
  end
end
