defmodule MobileCarWash.Repo.Migrations.AddEmailVerifiedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers) do
      add :email_verified_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:customers) do
      remove :email_verified_at
    end
  end
end
