defmodule MobileCarWash.Repo.Migrations.CreateMarketingPosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:marketing_posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :body, :text, default: ""
      add :image_url, :text
      add :channels, {:array, :text}, null: false, default: []
      add :persona_ids, {:array, :uuid}, default: []
      add :status, :text, null: false, default: "draft"
      add :scheduled_at, :utc_datetime_usec
      add :published_at, :utc_datetime_usec
      add :external_ids, :map, default: %{}
      add :error_message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:marketing_posts)
  end
end
