defmodule MobileCarWash.Repo.Migrations.BlockTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:block_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :day_of_week, :bigint, null: false
      add :start_hour, :bigint, null: false
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :service_type_id,
          references(:service_types,
            column: :id,
            name: "block_templates_service_type_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:block_templates, [:service_type_id, :day_of_week, :start_hour],
             name: "block_templates_unique_slot_index"
           )
  end

  def down do
    drop_if_exists unique_index(:block_templates, [:service_type_id, :day_of_week, :start_hour],
                     name: "block_templates_unique_slot_index"
                   )

    drop constraint(:block_templates, "block_templates_service_type_id_fkey")

    drop table(:block_templates)
  end
end
